In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [4]:
df=pd.read_csv('C:\\Users\\sahithi.s\\ai-ml-learning\\10-EDA\\apple_products_pricing_2020_2026.csv')
df

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               80000 non-null  str
 1   Platform           80000 non-null  str
 2   Product_Category   80000 non-null  str
 3   Model_Name         80000 non-null  str
 4   Condition          80000 non-null  str
 5   Launch_Price_USD   80000 non-null  int64
 6   Launch_Price_INR   80000 non-null  int64
 7   Current_Price_USD  80000 non-null  float64
 8   Current_Price_INR  80000 non-null  float64
 9   Discount_Pct       80000 non-null  float64
 10  Sale_Event         6649 non-null   str
 11  Stock_Status       80000 non-null  str
 12  Rating             80000 non-null  float64
 13  Reviews_Count      80000 non-null  int64
dtypes: float64(4), int64(3), str(7)
memory usage: 13.2 MB

In [10]:
string=["Platform","Product_Category","Model_Name","Condition","Sale_Event","Stock_Status"]
for val in string:
    print(val,df[val].value_counts())

Platform Platform
Flipkart    40043
Amazon      39957
Name: count, dtype: int64
Product_Category Product_Category
iPhone    28589
Mac       18020
Watch     17865
iPad      15526
Name: count, dtype: int64
Model_Name Model_Name
iPhone 14 Pro 128GB                 2734
iPad Air (4th Gen) 64GB             2677
iPad Pro 11-inch (M1) 128GB         2661
iPhone 17 128GB                     2652
iPhone 16 Pro 256GB                 2635
MacBook Pro 14-inch M4 Pro 512GB    2623
MacBook Air M2 256GB                2610
Apple Watch Series 8 (45mm)         2606
iPhone 13 128GB                     2605
iPhone 12 Pro 128GB                 2604
iPhone 15 Pro Max 256GB             2603
iPhone 15 128GB                     2602
Apple Watch Series 7 (45mm)         2600
MacBook Air M3 256GB                2589
iPad Air (5th Gen) 64GB             2583
iPad Pro 11-inch (M4) 256GB         2575
iPad (9th Gen) 64GB                 2573
Apple Watch Series 6 (44mm)         2572
iPhone 16 128GB                     2567
MacBook Pro 14-inch M2 Pro 512GB    2556
MacBook Air M1 256GB                2550
iPhone 13 Pro Max 256GB             2547
MacBook Pro 14-inch M3 Pro 512GB    2547
MacBook Pro 14-inch M1 Pro 512GB    2545
Apple Watch Ultra                   2544
iPhone 12 64GB                      2531
Apple Watch Series 9 (45mm)         2530
Apple Watch Series X (45mm)         2520
iPhone 14 128GB                     2509
Apple Watch Ultra 2                 2493
iPad Pro 12.9-inch (M2) 256GB       2457
Name: count, dtype: int64
Condition Condition
New                    59985
Renewed/Refurbished    20015
Name: count, dtype: int64
Sale_Event Sale_Event
Black Friday             2497
Big Billion Days         1579
Great Indian Festival    1504
Prime Day                1069
Name: count, dtype: int64
Stock_Status Stock_Status
In Stock        55034
Out of Stock    13475
Low Stock       11491
Name: count, dtype: int64

In [11]:
df.isnull().sum()

Date                     0
Platform                 0
Product_Category         0
Model_Name               0
Condition                0
Launch_Price_USD         0
Launch_Price_INR         0
Current_Price_USD        0
Current_Price_INR        0
Discount_Pct             0
Sale_Event           73351
Stock_Status             0
Rating                   0
Reviews_Count            0
dtype: int64

In [12]:
df['Sale_Event'].value_counts()

Sale_Event
Black Friday             2497
Big Billion Days         1579
Great Indian Festival    1504
Prime Day                1069
Name: count, dtype: int64

In [14]:
df[df['Sale_Event'].isnull()]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [15]:
'''in the null values of the column
when it fill the null values
ask these questions
1.is it important for your problem?or helpful or not 
2.if it is yes how to fill the null values or drop the null values
if the null values or samll we can drop the rows if the null values is big we can use anymethod the to fill the null values.
methods of filling null values
1.mean():if the column is float you can use the mean
2.median ():if the column is integer like is in the range of anything
3.Mode:if the column is categorical we can use the mode 
4.forwardfilling :we use the fffill when the data set has so many have outliers when apply the mean to the nulll it shows so much goes tpo outilers data when it 
removing of outlier we can remove most of the data.that's why me can use the ffill it to give range of the timme.
5.backwardfilling:when the first vales or null when it comes forwardfill most of the values or only values that'why we can backwardfilll
6.interpolation:It is the techniques we are uisng date and time datsets.It is draw line between the null valuesit give the more accurate values
.there is typei,linear interpolation:drawline wehn it comes there is osmuch of null values in between them it give the same value when time time forecasting iit give actual prediction
that's why we can spline interpolation.:it draws the quadratic ployrmnial line null values it doesn't come same value for the long null values.
7.inplace a value in the null value'''
df['Date'] = pd.to_datetime(df['Date'])
df['Sale_Event'] = df['Sale_Event'].fillna('Normal')
df

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,Normal,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,Normal,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,Normal,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,Normal,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,Normal,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,Normal,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,Normal,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,Normal,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,Normal,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,Normal,Low Stock,4.8,1022

In [17]:
df.isnull().sum()

Date                 0
Platform             0
Product_Category     0
Model_Name           0
Condition            0
Launch_Price_USD     0
Launch_Price_INR     0
Current_Price_USD    0
Current_Price_INR    0
Discount_Pct         0
Sale_Event           0
Stock_Status         0
Rating               0
Reviews_Count        0
dtype: int64