**Numpy**

Introduction


*   NumPy is a Python library used for working with arrays.
*   NumPy stands for Numerical Python.

Why Use NumPy?


*   In Python we have lists that serve the purpose of arrays, but they are slow to process.
*   NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [ ]:
''' Get started with Numpy
    Installation of Numpy'''
!pip install Numpy # Install it using this command:

Requirement already satisfied: Numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
#check the version of numpy
print(numpy.__version__)

NameError: name 'numpy' is not defined

In [ ]:
#Import the numpy
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]

In [ ]:
#NumPy is usually imported under the np alias.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr1=np.array([[1,2],[3,4]])

print(arr)
print(arr1)

[1 2 3 4 5]
[[1 2]
 [3 4]]

In [ ]:
#Create numpy array object
#We can create a NumPy ndarray object by using the array() function.
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

In [ ]:
'''To create an ndarray, we can pass a list,
 tuple or any array-like object into the array() method, and it will be converted into an ndarray:'''
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

In [ ]:
#Let's create 2D Array using numpy
arr=np.array([[1,2,3],[2,34,5]])
print(arr)
#check the number of dimensions
print(arr.ndim)

[[ 1  2  3]
 [ 2 34  5]]
2

In [ ]:
#Let's craete 3D Array using Numpy
arr=np.array([[[1,2,3],[4,4,5]],[[23,4,5],[7,8,9]]])
print(arr)
#check the dim of the array
print(arr.ndim)

[[[ 1  2  3]
  [ 4  4  5]]

 [[23  4  5]
  [ 7  8  9]]]
3

In [ ]:
x=x.reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

In [ ]:
x[1:,1:,1:]

array([[[17, 18, 19],
        [21, 22, 23]]])

In [ ]:
x[:,-2:,:]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
x[:,: ,::-1]

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])

In [ ]:
#let's create dimesnsion using the ndim
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print(arr.shape)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
(1, 1, 1, 1, 4)

In [ ]:
#Arrange
x=np.arange(2*3*4)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

In [ ]:
#accesing of the array Elements of 1D array
arr = np.array([1, 2, 3, 4])
print(arr[3])
print(arr[-1])
print(arr[2:])
print(arr[-3:-1:1])

4
4
[3 4]
[2 3]

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
#Slicing the row wise
print(arr[1,1:4])
#Slicing the column wise
print(arr[0:2, 3])

2nd element on 1st row:  2
[7 8 9]
[4 9]

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6

Data Types in Numpy



---


i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [ ]:
#Get the data type of an array object
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64

In [ ]:
'''NumPy uses the Unicode string data type (<U).

The number after U (6 in this case) means the maximum length of any string in the array.
'''
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6

In [ ]:
#Create an array with data type string
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1

In [ ]:
#A non integer string like 'a' can not be converted to integer (will raise an error):
arr = np.array(['a', '2', '3'], dtype='i')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#Converting a datatype using existing arrays
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int32

In [ ]:
#I wnat to chnage this array into boolean
arr = np.array([1, 0, 3])
print(arr.dtype)
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

int64
[ True False  True]
bool

In [ ]:
#Let's Move to the functions in NUmpy
''' Copy VS View
    The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

    The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

    The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.
'''
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)
x[2]=33
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[ 1  2 33  4  5]

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
x[2]=33
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]
[42  2 33  4  5]
[42  2 33  4  5]

In [ ]:
#Shape of the Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
#(2,4) 2 represents
print(arr.shape)

(2, 4)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

In [ ]:
#Reshape the array only consider the shape of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
#Flattening array means converting a multidimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]

In [ ]:
#Iterating Arrays
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3

In [ ]:
#Iterating arrays in 2 dimansional array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]

In [ ]:
#Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8

In [ ]:
#Iterating Arrays using slicing
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7

In [ ]:
#Enumerated Iteration Using ndenumerate()
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8

In [ ]:
#Joining Arrays using Concatenate
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]

In [ ]:
#Joining Arrays using axis like rowwise and column wise
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)
print(np.concatenate((arr1, arr2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]

In [ ]:
#Joining Arrays Using Stack Functions
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
#arr1 = np.array([1, 2, 3])

#arr2 = np.array([4, 5, 6])
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr = np.stack((arr1, arr2), axis=1)

print(arr)
print(np.stack((arr1, arr2), axis=0))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

In [ ]:
#Stacking along rows
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]

In [ ]:
#stacking along columns
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]

In [ ]:
#stacking along depth
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]

In [ ]:
#floor() always rounds towards negative infinity.
#ceil() always rounds towards positive infinity.
nums=np.arange(5)
print(nums)
print(nums*10)
print(np.sqrt(nums))
print(np.isnan(nums))
print(np.ceil(nums))
print(max(nums))

[0 1 2 3 4]
[ 0 10 20 30 40]
[0.         1.         1.41421356 1.73205081 2.        ]
[False False False False False]
[0. 1. 2. 3. 4.]
4

In [ ]:
#Spillting Array:Splitting breaks one array into multiple.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]

In [ ]:
#spiltiing 2DArray
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

In [ ]:
#Numpy Searching Arrays
#Search an array for a certain value, and return the indexes that get a match.
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)

In [ ]:
#Sorting Arrays
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]

In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)[::-1])

[3 2 1 0]

In [ ]:
#Sorting order array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr,axis=1))

[[2 3 4]
 [0 1 5]]

In [ ]:
#Random Generates the number
from numpy import random

x = random.randint(100,size=(5))

print(x)

[48 61  5  4 93]

In [ ]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x = random.randint(100, size=(3, 5))

print(x)

Pandas

Pandas is  a python Library used for working with datasets.
It has functions for analyzing, cleaning, exploring, and manipulating data.

In [ ]:
#installation of pandas
!pip install pandas

In [ ]:
import pandas as pd
print([pd.__version__])

['2.2.2']

In [ ]:
#create a series.
#Series is like a column in a table
df=pd.Series([1,2,3,4])
print(df)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#we have to create labels
a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [ ]:
#create a dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [ ]:
#Create a Series using only data from "day1" and "day2":
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [ ]:
'''DataFrames
   Data sets in Pandas are usually multi-dimensional tables, called DataFrames.
   A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
'''
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
#Access the first row using loc
myvar.loc[0]

calories    420
duration     50
Name: 0, dtype: int64

In [ ]:
myvar.loc[1]

calories    380
duration     40
Name: 1, dtype: int64

In [ ]:
'''
  what's the difference between loc and iloc
  loc:Selects data based on the labels (names) of rows and columns.
  iloc:Selects data based on the integer positions (indices, starting from 0) of rows and columns.
'''
data = {'col1': [10, 20, 30], 'col2': [40, 50, 60]}
df = pd.DataFrame(data, index=['A', 'B', 'C'])
print(df)
# Using loc
print(df.loc['A', 'col1'])  # Selects value at row 'A', column 'col1'

# Using iloc
print(df.iloc[0, 0])

   col1  col2
A    10    40
B    20    50
C    30    60
10
10

In [ ]:
#Read json file
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [ ]:
columns=['name','age','gender','job']
user1=pd.DataFrame([['sahithi',20,'F','student'],
                    ['ramu',21,'M','student']],columns=columns)

In [ ]:
user2=pd.DataFrame([['Pathi',20,'M','student'],
                    ['Durga',21,'F','student']],columns=columns)
user3=pd.DataFrame([['Kishore',20,'M','scientist'],
                    ['krishna',21,'M','manager']],columns=columns)

In [ ]:
user4=pd.DataFrame(dict(name=['Nani','Depithi'],
                        age=[33,44],gender=['M','F'],
                        job=['engineer','scientist']))
print(user4)

      name  age gender        job
0     Nani   33      M   engineer
1  Depithi   44      F  scientist

In [ ]:
users=pd.concat([user1,user2,user3,user4])
users

      name  age gender        job
0  sahithi   20      F    student
1     ramu   21      M    student
0    Pathi   20      M    student
1    Durga   21      F    student
0  Kishore   20      M  scientist
1  krishna   21      M    manager
0     Nani   33      M   engineer
1  Depithi   44      F  scientist

In [ ]:
user5=pd.DataFrame(dict(name=['sahithi','Pathi','Durga', 'Krishna','Nani','Depithi'],
                        height=[165,180,171,160,184,165]))
print(user5)

      name  height
0  sahithi     165
1    Pathi     180
2    Durga     171
3  Krishna     160
4     Nani     184
5  Depithi     165

In [ ]:
m=pd.merge(users,user5,on="name")
print(m)

      name  age gender        job  height
0  sahithi   20      F    student     165
1    Pathi   20      M    student     180
2    Durga   21      F    student     171
3     Nani   33      M   engineer     184
4  Depithi   44      F  scientist     165

In [ ]:
users=pd.merge(users,user5,on='name',how='outer')
print(users)

      name   age gender        job  height
0  Depithi  44.0      F  scientist   165.0
1    Durga  21.0      F    student   171.0
2  Kishore  20.0      M  scientist     NaN
3  Krishna   NaN    NaN        NaN   160.0
4     Nani  33.0      M   engineer   184.0
5    Pathi  20.0      M    student   180.0
6  krishna  21.0      M    manager     NaN
7     ramu  21.0      M    student     NaN
8  sahithi  20.0      F    student   165.0

In [ ]:
'''Consider a DataFrame with columns like Name, Math, and Science. Using melt(),
 you can transform it so that Name remains an identifier, and Math and Science
  are unpivoted into a new Subject column and a Score column.

  Pivot-->Rows to columns when convert the rows into columns one column into multiple cloumns.we used Present information in a new perspective form
  UnPivot -->Collumns to rows eaiser to anlaysis of the dataframe .we used in the easier to perform on a row-by-row basis
'''

data = {'Name': ['Alice', 'Bob'],
        'Math': [90, 85],
        'Science': [88, 92]}
df = pd.DataFrame(data)
print(df)
# Melt the DataFrame
melted_df = pd.melt(df, id_vars=['Name'], var_name='Subject', value_name='Score')

print('melted df',melted_df)

    Name  Math  Science
0  Alice    90       88
1    Bob    85       92
melted df     Name  Subject  Score
0  Alice     Math     90
1    Bob     Math     85
2  Alice  Science     88
3    Bob  Science     92

In [ ]:
'''Use pandas.pivot() when your data strictly adheres to a one-to-one mapping
between the index and columns values, and you don't need to perform any aggregation.'''
#Need to aggregate data
print(melted_df.pivot(index='Name',columns='Subject',values='Score'))

Subject  Math  Science
Name
Alice      90       88
Bob        85       92

In [ ]:
#read the csv files
df=pd.read_csv('/content/train.csv')
df

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#Access the top rows
df.head()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1

In [ ]:
#retrieve the top 10 rows
df.head(10)

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1
5,5,24,admin.,single,secondary,no,1882,yes,no,cellular,20,apr,1010,3,-1,0,unknown,0
6,6,39,blue-collar,married,secondary,no,0,no,no,telephone,21,nov,90,1,-1,0,unknown,0
7,7,50,admin.,single,secondary,no,1595,no,no,telephone,31,jul,49,25,-1,0,unknown,0
8,8,46,blue-collar,married,primary,no,1463,no,no,cellular,4,aug,50,1,-1,0,unknown,0
9,9,39,management,divorced,tertiary,no,25,yes,no,cellular,8,may,119,1,-1,0,unknown,0

In [ ]:
df.tail()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
df.tail(10)

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
749990,749990,34,blue-collar,married,secondary,no,1385,no,no,cellular,26,apr,134,2,-1,0,unknown,0
749991,749991,52,management,married,tertiary,no,1359,no,no,cellular,19,aug,124,5,-1,0,unknown,0
749992,749992,56,services,married,secondary,no,2089,yes,no,cellular,20,apr,78,3,305,1,failure,0
749993,749993,41,management,married,secondary,yes,-1300,yes,yes,cellular,17,nov,129,1,-1,0,unknown,0
749994,749994,31,housemaid,single,secondary,no,594,no,no,cellular,4,feb,137,1,-1,0,unknown,0
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
df.index

RangeIndex(start=0, stop=750000, step=1)

In [ ]:
df.columns

Index(['id', 'age', 'job', 'marital', 'education', 'default', 'balance',
       'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign',
       'pdays', 'previous', 'poutcome', 'y'],
      dtype='object')

In [ ]:
df.dtypes

id            int64
age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y             int64
dtype: object

In [ ]:
df.shape

(750000, 18)

In [ ]:
df.values

array([[0, 42, 'technician', ..., 0, 'unknown', 0],
       [1, 38, 'blue-collar', ..., 0, 'unknown', 0],
       [2, 36, 'blue-collar', ..., 0, 'unknown', 0],
       ...,
       [749997, 50, 'blue-collar', ..., 0, 'unknown', 0],
       [749998, 32, 'technician', ..., 0, 'unknown', 0],
       [749999, 42, 'technician', ..., 7, 'failure', 0]], dtype=object)

In [ ]:
#that gives you more information about the data set.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 18 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         750000 non-null  int64
 1   age        750000 non-null  int64
 2   job        750000 non-null  object
 3   marital    750000 non-null  object
 4   education  750000 non-null  object
 5   default    750000 non-null  object
 6   balance    750000 non-null  int64
 7   housing    750000 non-null  object
 8   loan       750000 non-null  object
 9   contact    750000 non-null  object
 10  day        750000 non-null  int64
 11  month      750000 non-null  object
 12  duration   750000 non-null  int64
 13  campaign   750000 non-null  int64
 14  pdays      750000 non-null  int64
 15  previous   750000 non-null  int64
 16  poutcome   750000 non-null  object
 17  y          750000 non-null  int64
dtypes: int64(9), object(9)
memory usage: 103.0+ MB

In [ ]:
df['age']

0         42
1         38
2         36
3         27
4         26
          ..
749995    29
749996    69
749997    50
749998    32
749999    42
Name: age, Length: 750000, dtype: int64

In [ ]:
df[['age','poutcome']]

        age poutcome
0        42  unknown
1        38  unknown
2        36  unknown
3        27  unknown
4        26  unknown
...     ...      ...
749995   29  unknown
749996   69  unknown
749997   50  unknown
749998   32  unknown
749999   42  failure

[750000 rows x 2 columns]

In [ ]:
users=df.copy()
users

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
df.sort_values(by='age')

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
531385,531385,18,blue-collar,single,secondary,no,3,no,no,cellular,27,jun,143,1,-1,0,unknown,0
568876,568876,18,services,married,secondary,no,533,no,no,telephone,6,aug,293,10,-1,0,unknown,0
392966,392966,18,student,single,tertiary,no,846,no,no,cellular,27,may,116,2,97,1,other,0
138704,138704,18,student,single,secondary,no,2143,no,no,cellular,6,jul,265,3,178,5,success,1
143487,143487,18,student,single,primary,no,484,no,no,cellular,10,aug,192,2,184,3,success,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465360,465360,94,retired,divorced,primary,no,521,no,no,cellular,18,feb,212,1,92,4,success,1
449210,449210,94,retired,married,unknown,no,12039,no,no,telephone,30,apr,516,4,-1,0,unknown,1
557988,557988,95,retired,divorced,primary,no,852,no,no,telephone,1,apr,223,2,-1,0,unknown,1
283611,283611,95,retired,married,secondary,no,4984,no,no,telephone,26,oct,88,1,-1,0,unknown,0
551450,551450,95,retired,married,secondary,no,4657,no,no,telephone,31,mar,466,1,-1,0,unknown,1

In [ ]:
df.describe()

,id,age,balance,day,duration,campaign,pdays,previous,y
count,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000
mean,374999.500000,40.926395,1204.067397,16.117209,256.229144,2.577008,22.412733,0.298545,0.120651
std,216506.495284,10.098829,2836.096759,8.250832,272.555662,2.718514,77.319998,1.335926,0.325721
min,0.000000,18.000000,-8019.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,0.000000
25%,187499.750000,33.000000,0.000000,9.000000,91.000000,1.000000,-1.000000,0.000000,0.000000
50%,374999.500000,39.000000,634.000000,17.000000,133.000000,2.000000,-1.000000,0.000000,0.000000
75%,562499.250000,48.000000,1390.000000,21.000000,361.000000,3.000000,-1.000000,0.000000,0.000000
max,749999.000000,95.000000,99717.000000,31.000000,4918.000000,63.000000,871.000000,200.000000,1.000000

In [ ]:
#check the null values present in the dataset
df.isnull()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
749996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
749997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
749998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
749999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#when I wnat to see the whole count of null values
df.isnull().sum()

id           0
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
#Null values in the dataset it leads to give wrong analysis you have to remove the null values
new_df = df.dropna()

new_df

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
#If you want to change the original DataFrame, use the inplace = True argument
df.dropna(inplace = True)
df

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
#we have another option for nullvalues to fill the values in that place
df.fillna(12,inplace=True)
df

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
#mean,
df['age'].mean()

np.float64(40.92639466666667)

In [ ]:
df['poutcome'].mode()

0    unknown
Name: poutcome, dtype: object

In [ ]:
df['day'].median()

17.0

In [ ]:
#Replacing the values of the specific cloumn and specific value
df.loc[0, 'age'] = 200
df

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,200,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
df.loc[df.age.isnull(),'age']=df.age.mean()

/tmp/ipython-input-1486963822.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '40.92639466666667' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df.age.isnull(),'age']=df.age.mean()

In [ ]:
#To know the duplicate values in a dataset
df.duplicated()

1         False
2         False
3         False
4         False
5         False
          ...
749995    False
749996    False
749997    False
749998    False
749999    False
Length: 749358, dtype: bool

In [ ]:
#Removing the duplicate values
df.drop_duplicates(inplace = True)
df

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1
5,5,24,admin.,single,secondary,no,1882,yes,no,cellular,20,apr,1010,3,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,29,services,single,secondary,no,1282,no,yes,unknown,4,jul,1006,2,-1,0,unknown,1
749996,749996,69,retired,divorced,tertiary,no,631,no,no,cellular,19,aug,87,1,-1,0,unknown,0
749997,749997,50,blue-collar,married,secondary,no,217,yes,no,cellular,17,apr,113,1,-1,0,unknown,0
749998,749998,32,technician,married,secondary,no,-274,no,no,cellular,26,aug,108,6,-1,0,unknown,0
749999,749999,42,technician,married,secondary,no,1559,no,no,cellular,4,aug,143,1,1,7,failure,0

In [ ]:
#Finding the realtionships of the columns
newcolumns=df[['age','balance']]
newcolumns.corr()

              age   balance
age      1.000000  0.060786
balance  0.060786  1.000000